# Generated by Django 5.1.7 on 2025-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
        migrations.AddField(
            model_name='notes',
            name='target_date',
            field=models.DateTimeField(null=True, verbose_name='target_date'),
        ),
        migrations.AddField(
            model_name='notes',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(max_length=300, verbose_name='note'),
        ),
    ]
