# Generated by Django 5.1.7 on 2025-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_notes_date_notes_target_date_notes_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(max_length=300, null=True, verbose_name='note'),
        ),
    ]
