# Generated by Django 5.1.7 on 2025-05-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user'], 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
    ]
