# Generated by Django 5.1.7 on 2025-05-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
