# Generated by Django 5.1.7 on 2025-04-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_notes_username_alter_notes_note_customuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
