# Generated by Django 5.1.7 on 2025-04-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
