# Generated by Django 5.1.6 on 2025-03-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_grouplink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.CharField(max_length=100, null=True, verbose_name='place'),
        ),
    ]
