# Generated by Django 5.1.6 on 2025-03-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_name',
            field=models.CharField(max_length=100, verbose_name='lesson_name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='teacher'),
        ),
    ]
