# Generated by Django 5.1.7 on 2025-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_grouplink_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplink',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='group_name'),
        ),
    ]
