# Generated by Django 5.1.7 on 2025-04-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lessons', to='schedule.grouplink'),
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='week')),
                ('lesson_name', models.CharField(max_length=300, verbose_name='lesson_name')),
                ('lesson_type', models.CharField(max_length=100, verbose_name='lesson_type')),
                ('teacher', models.CharField(max_length=300, null=True, verbose_name='teacher')),
                ('place', models.CharField(max_length=300, null=True, verbose_name='place')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='username')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.grouplink')),
            ],
            options={
                'verbose_name': 'User schedule',
                'verbose_name_plural': 'Users schedule',
            },
        ),
    ]
