# Generated by Django 5.1.7 on 2025-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='week')),
                ('lesson_name', models.CharField(max_length=300, verbose_name='lesson_name')),
                ('lesson_type', models.CharField(max_length=100, verbose_name='lesson_type')),
                ('teacher', models.CharField(max_length=300, null=True, verbose_name='teacher')),
                ('place', models.CharField(max_length=300, null=True, verbose_name='place')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
            ],
            options={
                'verbose_name': 'User schedule',
                'verbose_name_plural': 'Users schedule',
            },
        ),
    ]
