# Generated by Django 5.1.7 on 2025-04-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_schedule_group_name_userschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='userschedule',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='userschedule',
            name='user_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.grouplink'),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='schedule.grouplink'),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.TextField(max_length=300, null=True, verbose_name='note_content')),
                ('note_date', models.DateTimeField(null=True, verbose_name='note_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['user'],
            },
        ),
    ]
