# Generated by Django 5.1.7 on 2025-05-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='group_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='custom_lessons', to='schedule.grouplink'),
            preserve_default=False,
        ),
    ]
