# Generated by Django 5.1.7 on 2025-05-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_userschedule_user_alter_notes_note_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userschedule',
            options={'ordering': ['user'], 'verbose_name': 'User schedule', 'verbose_name_plural': 'Users schedule'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_date',
            field=models.DateTimeField(default='2025-04-07T16:30:00Z', verbose_name='note_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
