# Generated by Django 5.1.7 on 2025-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_userschedule_options_alter_notes_note_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
