# Generated by Django 5.1.7 on 2025-05-27 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_userschedule_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycledEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=300, verbose_name='teacher')),
                ('place', models.CharField(max_length=300, verbose_name='place')),
                ('lesson_name', models.CharField(max_length=300, verbose_name='lesson_name')),
                ('lesson_type', models.CharField(max_length=100, verbose_name='lesson_type')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('every_week', models.BooleanField(default=True, verbose_name='every_week')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.grouplink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycled event',
                'verbose_name_plural': 'Cycled events',
                'ordering': ['user'],
            },
        ),
    ]
