# Generated by Django 5.1.7 on 2025-05-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
