# Generated by Django 5.1.7 on 2025-05-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_cycledevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycledevents',
            old_name='group',
            new_name='group_name_id',
        ),
    ]
